import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "q-sm": "4px",
        "q-md": "8px",
        "q-lg": "12px",
        "q-xl": "16px",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Marketing page tokens (namespaced to avoid app conflicts)
        "mkt-primary": "#0F172A",
        "mkt-secondary": "#06B6D4",
        "mkt-background": "#F7F9FB",
        "mkt-error": "#EF4444",
        // Marketing tokens (no conflict with app)
        "brand-navy": "#0F172A",
        "brand-teal": "#06B6D4",
        "brand-amber": "#F59E0B",
        "teal-brand": "#06B6D4",
        "amber-brand": "#F59E0B",
        "surface": "#F7F9FB",
        "surface-tint": "#565e74",
        "surface-container": "#ECEEF0",
        "surface-container-low": "#F2F4F6",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#FFFFFF",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191C1E",
        "on-surface-variant": "#45464d",
        "on-background": "#191C1E",
        "on-primary": "#FFFFFF",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-container": "#7c839b",
        "primary-container": "#131b2e",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary": "#FFFFFF",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-container": "#006172",
        "secondary-container": "#57dffe",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "tertiary": "#D97706",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#2a1700",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary-container": "#b87500",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#bec6e0",
        // Quiz-specific teal (darker than brand-teal, matches Stitch)
        "mkt-teal": "#00687a",
        // Qashivo q- design tokens
        "q-bg": {
          page: "var(--q-bg-page)",
          surface: "var(--q-bg-surface)",
          "surface-hover": "var(--q-bg-surface-hover)",
          "surface-alt": "var(--q-bg-surface-alt)",
          input: "var(--q-bg-input)",
          sidebar: "var(--q-bg-sidebar)",
        },
        "q-text": {
          primary: "var(--q-text-primary)",
          secondary: "var(--q-text-secondary)",
          tertiary: "var(--q-text-tertiary)",
          muted: "var(--q-text-muted)",
        },
        "q-border": {
          DEFAULT: "var(--q-border-default)",
          hover: "var(--q-border-hover)",
          strong: "var(--q-border-strong)",
        },
        "q-money-in": {
          DEFAULT: "var(--q-money-in-text)",
          bg: "var(--q-money-in-bg)",
          border: "var(--q-money-in-border)",
        },
        "q-risk": {
          DEFAULT: "var(--q-risk-text)",
          bg: "var(--q-risk-bg)",
          border: "var(--q-risk-border)",
        },
        "q-attention": {
          DEFAULT: "var(--q-attention-text)",
          bg: "var(--q-attention-bg)",
          border: "var(--q-attention-border)",
        },
        "q-info": {
          DEFAULT: "var(--q-info-text)",
          bg: "var(--q-info-bg)",
          border: "var(--q-info-border)",
        },
        "q-accent": {
          DEFAULT: "var(--q-accent)",
          hover: "var(--q-accent-hover)",
          bg: "var(--q-accent-bg)",
        },
        "q-vip": {
          DEFAULT: "var(--q-vip-text)",
          bg: "var(--q-vip-bg)",
        },
      },
      fontFamily: {
        sans: ["DM Sans", "-apple-system", "BlinkMacSystemFont", "San Francisco", "Segoe UI", "system-ui", "sans-serif"],
        heading: ["Archivo", "sans-serif"],
        display: ["Archivo", "sans-serif"],
        mono: ["SF Mono", "Menlo", "Monaco", "Courier New", "monospace"],
        // Marketing fonts
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        // Qashivo q- fonts
        "q-sans": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "q-mono": ["JetBrains Mono", "SF Mono", "Fira Code", "Cascadia Code", "monospace"],
      },
      spacing: {
        "q-xs": "4px",
        "q-sm": "8px",
        "q-md": "12px",
        "q-lg": "16px",
        "q-xl": "24px",
        "q-2xl": "32px",
        "q-3xl": "48px",
      },
      fontSize: {
        "q-hero": ["32px", { lineHeight: "1.1", fontWeight: "600" }],
        "q-metric": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "q-page-title": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "q-section": ["16px", { lineHeight: "1.4", fontWeight: "600" }],
        "q-body": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "q-body-medium": ["14px", { lineHeight: "1.6", fontWeight: "500" }],
        "q-small": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "q-caption": ["11px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 5px rgba(6, 182, 212, 0.2)" },
          "50%": { boxShadow: "0 0 20px rgba(6, 182, 212, 0.4)" },
        },
        "breath-glow-teal": {
          "0%, 100%": { boxShadow: "0 0 0px rgba(6, 182, 212, 0)", borderColor: "rgba(6, 182, 212, 0.2)" },
          "50%": { boxShadow: "0 0 15px rgba(6, 182, 212, 0.3)", borderColor: "rgba(6, 182, 212, 0.6)" },
        },
        "bounce-in": {
          "0%": { transform: "scale(0)", opacity: "0" },
          "70%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "glow-pulse": "glow-pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "breath-glow-teal": "breath-glow-teal 4s ease-in-out infinite",
        "bounce-in": "bounce-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
