import { eq, and, lt, ne } from "drizzle-orm";
import { db } from "../db";
import { tenants, promisesToPay, invoices, actions } from "@shared/schema";

interface BreachDetectorConfig {
  checkIntervalMinutes: number; // How often to check for breaches (e.g., 60 min)
  enabled: boolean;
  runOnStartup: boolean;
}

/**
 * PTP Breach Detector
 * 
 * Monitors promises to pay and detects breaches when:
 * - Promise date has passed
 * - Invoice is still unpaid
 * - Promise status is still 'active'
 * 
 * When a breach is detected:
 * 1. Updates promise status to 'breached'
 * 2. Sets breachedAt timestamp
 * 3. Creates a follow-up action for the collector
 */
class PTPBreachDetector {
  private intervalId: NodeJS.Timeout | null = null;
  private config: BreachDetectorConfig;

  constructor(config: BreachDetectorConfig = { 
    checkIntervalMinutes: 60, // Check every hour
    enabled: true, 
    runOnStartup: true 
  }) {
    this.config = config;
  }

  /**
   * Start the PTP breach detector
   */
  start(): void {
    if (this.intervalId) {
      console.log("PTP breach detector already running");
      return;
    }

    if (!this.config.enabled) {
      console.log("PTP breach detector disabled by configuration");
      return;
    }

    console.log(`🚀 Starting PTP breach detector (checking every ${this.config.checkIntervalMinutes} minutes)`);

    // Run immediately on startup if configured
    if (this.config.runOnStartup) {
      setTimeout(() => {
        this.checkForBreaches();
      }, 10000); // Wait 10 seconds for app startup
    }

    // Set up recurring check
    this.intervalId = setInterval(
      () => this.checkForBreaches(),
      this.config.checkIntervalMinutes * 60 * 1000
    );

    console.log("✅ PTP breach detector started successfully");
  }

  /**
   * Stop the PTP breach detector
   */
  stop(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    console.log("🛑 PTP breach detector stopped");
  }

  /**
   * Check for breached promises across all tenants
   */
  private async checkForBreaches(): Promise<void> {
    try {
      console.log("🔍 Checking for breached promises to pay...");
      
      const now = new Date();
      const allTenants = await db.select().from(tenants);
      
      let totalBreaches = 0;

      for (const tenant of allTenants) {
        try {
          const breachCount = await this.checkTenantBreaches(tenant.id, now);
          totalBreaches += breachCount;
        } catch (error: any) {
          console.error(`❌ Error checking breaches for tenant ${tenant.id}:`, error.message);
        }
      }

      if (totalBreaches > 0) {
        console.log(`⚠️  Found ${totalBreaches} breached promise(s) to pay`);
      } else {
        console.log("✅ No breached promises found");
      }
    } catch (error: any) {
      console.error("❌ PTP breach detector error:", error.message);
    }
  }

  /**
   * Check for breaches in a specific tenant
   */
  private async checkTenantBreaches(tenantId: string, now: Date): Promise<number> {
    // Find all active promises where the promised date has passed
    const activePromises = await db
      .select({
        promise: promisesToPay,
        invoice: invoices
      })
      .from(promisesToPay)
      .leftJoin(invoices, eq(promisesToPay.invoiceId, invoices.id))
      .where(and(
        eq(promisesToPay.tenantId, tenantId),
        eq(promisesToPay.status, 'active'),
        lt(promisesToPay.promisedDate, now)
      ));

    let breachCount = 0;

    for (const { promise, invoice } of activePromises) {
      // Check if the invoice is still unpaid
      if (invoice && invoice.status !== 'paid') {
        // Mark the promise as breached
        await db
          .update(promisesToPay)
          .set({
            status: 'breached',
            breachedAt: now,
            updatedAt: now
          })
          .where(eq(promisesToPay.id, promise.id));

        // Create a follow-up action for the collector
        await db.insert(actions).values({
          tenantId: tenantId,
          invoiceId: promise.invoiceId,
          contactId: promise.contactId,
          userId: null, // System-generated action
          type: 'note',
          status: 'open',
          subject: 'Broken Promise to Pay',
          content: `Customer ${promise.contactName} failed to pay ${promise.amount} by ${promise.promisedDate.toISOString().split('T')[0]}. Follow-up required.`,
          metadata: {
            ptpId: promise.id,
            promisedAmount: promise.amount,
            promisedDate: promise.promisedDate,
            breachType: 'payment_not_received',
            autoGenerated: true
          },
          aiGenerated: false,
          source: 'automated'
        });

        console.log(`⚠️  Promise breached: ${promise.id} (Invoice ${invoice.invoiceNumber}, ${promise.amount} due ${promise.promisedDate.toISOString().split('T')[0]})`);
        breachCount++;
      }
    }

    return breachCount;
  }
}

// Create and export singleton instance
const ptpBreachDetector = new PTPBreachDetector();

// Export the detector instance
export { ptpBreachDetector };
